[theme]
primaryColor = "#386da8"
backgroundColor = "#d4e0e8"
secondaryBackgroundColor = "#c6d6e1"
textColor = "#1d2730"
font = "sans serif"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
